base: Build flatpak 1.15.4 again
1.15.6+ makes our CI very very sad, and even more sad
all the people that have to debug it.

We run into the following error for now, which is likely
cause by this [1] bubblewrap commit

```
bwrap: cannot open /proc/sys/user/max_user_namespaces: Read-only file system
Error: module xcursorgen: Child process exited with code 1
```

Revert so CI is green again, hopefully, and we can take a closer look at
a later time.

[1] https://github.com/containers/bubblewrap/commit/b5f672355b916e6e59dad5ec9ca55aa90afe8a90